name = "wite-env-example"
main = "dist/worker.js"
compatibility_date = "2024-12-01"

[build]
command = "pnpm build:worker"
watch_dir = "src"

# Wasm modules referenced via URL are served as static assets
[site]
bucket = "./dist/assets"
