// Type declarations for direct .wasm imports (Cloudflare Workers)
declare module "*.wasm" {
  const wasmModule: WebAssembly.Module;
  export default wasmModule;
}

// Web Worker wasm imports: functions return Promises
declare module "*.wasm?wite-worker" {
  export function __witeTerminate(): void;
  // Specific exports are defined by the .wasm.d.ts generated by the plugin
}
